spring:
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  jpa:
    database: H2
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false